server:
  port: 8012

spring:
  application:
    name: service-verification-code
  redis:
    host: 192.168.237.136
    password:
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
